# Generated by Django 5.1.3 on 2024-11-21 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_customuser_email_alter_customuser_groups_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="customuser",
            name="unique_email",
        ),
    ]
