# Generated by Django 5.1.3 on 2024-11-29 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_alter_customuser_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("0", "Super Admin"), ("1", "Recruiter"), ("2", "User")],
                default="2",
                max_length=50,
            ),
        ),
    ]
